### ISSUE TITLE
problem when I send bp from desktop wallet to web wallet

### ISSUE THREAD

**Issue by mmo1828** [bpcomunity/bitpaycoin#1]
Hello;
I have problem when I send bp from desktop wallet to web wallet.
(web wallet didn't receive bp)
Who can I report this problem ?
Please help me
----------------
Status: 118 confirmations
Date: 2/11/2017 09:03
To: mmo0838 BD53aGmzUnCQxegu8eoXL15KmL2xb9ga81
Debit: -1.00 BP
Transaction fee: -0.00001 BP
Net amount: -1.00001 BP
Transaction ID: 07eba13de776eeba7d4be1a2a0027e6aa2894a5bb338fc5e61ce99cc49b5b644

-------------------
Status: 139 confirmations
Date: 2/11/2017 08:43
To: quanghuylogic BNrsz5PWWY1cdMftFzWoDH8urLhuednZXi
Debit: -1.00 BP
Transaction fee: -0.00001 BP
Net amount: -1.00001 BP
Transaction ID: a32f745b5c23d4d11060e44f4796640092e0810b7067435f9df30718deea4f94
---------------------
Status: 772 confirmations
Date: 1/11/2017 21:24
To: mmo1828-webwallet B6gSdwNQXhcPgxKLtvnrqwBiKeX1wzgYfW
Debit: -80.00 BP
Transaction fee: -0.00001 BP
Net amount: -80.00001 BP
Transaction ID: c183052dfd0d52be3e2fb122b261b40b27f5d652a0cb116e99802cae9b8ad8b6
--------------------------
Many thanks

**Comment by bpcomunity** [comment]
Yess
Please read this https://bitpaycoin.co/bitpaycoin-on-new-algorithm-x15
it appear on your dashboard

**Comment by mmo1828** [comment]
Hi
Desktop bitpaywallet v1.3.1.2 is new or old version ?
